before:
  hooks:
    - go mod tidy
builds:
  - id: clio
    binary: clio
    ldflags:
      - -w -s
    tags:
      - -fts5
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=gcc
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
