name: Build release artifacts and draft release

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: mlugg/setup-zig@v1
      - name: Go build
        run: CGO_ENABLED=1 CC="zig cc" CXX="zig cc" go build --tags "fts5" -trimpath -ldflags "-s -w" ./main.go
      - name: list
        run: ls -lah

