name: Build release artifacts and draft release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1

