name: Build release artifacts and draft release

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: mlugg/setup-zig@v1
      - name: Go build x86
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="zig cc -target x86_64-linux-musl" CXX="zig c++ -target x86_64-linux-musl" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-x86_64-musl .
      - name: Go build arm static
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux-musl" CXX="zig c++ -target aarch64-linux-musl" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64-musl .
      - name: Go build arm dynamic
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux-gnu" CXX="zig c++ -target aarch64-linux-gnu" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64-gnuc .
      - name: list
        run: ls -lah dist
      - name: Go build darwin x86
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 CC="zig cc -target x86_64-linux-musl" CXX="zig c++ -target x86_64-macos" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-darwin-x86_64 .
      - name: Go build darwin arm 
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=arm64 CC="zig cc -target aarch64-macos" CXX="zig c++ -target aarch64-macos" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64 .

