name: Build release artifacts and draft release

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: mlugg/setup-zig@v1
      - name: Go build native
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="zig cc -target x86_64-linux-musl" CXX="zig cc -target x86_64-linux-musl" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-x86_64-musl .
      - name: Go build arm
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target arm-linux-musleabihf" CXX="zig cc -target arm-linux-musleabihf" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64 .
      - name: list
        run: ls -lah dist
