name: Build release artifacts and draft release

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache-dependency-path: subdir/go.sum
      - uses: mlugg/setup-zig@v1
      - name: Go build x86
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 CC="zig cc -target x86_64-linux-musl" CXX="zig c++ -target x86_64-linux-musl" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-x86_64-musl .
      - name: Go build arm static
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux-musl" CXX="zig c++ -target aarch64-linux-musl" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64-musl .
      - name: Go build arm dynamic
        run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC="zig cc -target aarch64-linux-gnu" CXX="zig c++ -target aarch64-linux-gnu" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-linux-arm64-gnuc .
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            dist/clio-*
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: clio-linux
          path: dist/clio*

  build-macos-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
          cache-dependency-path: subdir/go.sum
      - name: Build
        run: GOOS=darwin GOARCH=amd64 CGO_ENABLED=1 go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-macos-x86_64 .
      - name: Build ARM
        run: GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-macos-aarch64 .
      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            dist/clio-*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: clio-macos
          path: dist/clio*

  draft-release:
    needs: [build-linux-binary, build-macos-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make directories
        run: |
          mkdir -p ./clio-build/linux
          mkdir -p ./clio-build/macos
      - name: Download linux binaries
        uses: actions/download-artifact@v4
        with:
          name: clio-linux
          path: ./clio-build/linux
      - name: Download macos binaries
        uses: actions/download-artifact@v4
        with:
          name: clio-macos
          path: ./clio-build/macos
      - name: Merge checksum file
        run: |
          cd ./clio-build
          cat ./darwin/clio*checksums.txt >> checksums.txt
          rm ./linux/clio*checksums.txt
          cat ./macos/clio*checksums.txt >> checksums.txt
          rm ./macos/clio*checksums.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            .clio-build/*.**
