name: Build release artifacts and draft release

on:
  push:
    # tags:
    #   - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: mlugg/setup-zig@v1
      - name: Go build
        run: CGO_ENABLED=1 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CC="zig cc" CXX="zig cc" go build --tags "fts5" -trimpath -ldflags "-s -w" -o dist/clio-${{ matrix.os }}-${{ matrix.arch }} .
      - name: list
        run: ls -lah dist
